services:
  user:
    build: 
      context: ./user
      dockerfile: Dockerfile
    container_name: usercontainer
    command: uvicorn user.index:app --host 0.0.0.0 --port 80 --reload --reload-include *
    ports:
      - "80:80"
    volumes:
      - .:/GrimReaper/user

  ambulance:
    build: 
      context: ./ambulance
      dockerfile: Dockerfile
    container_name: ambulancecontainer
    command: uvicorn ambulance.index:app --host 0.0.0.0 --port 8000 --reload --reload-include *
    ports:
      - "8000:8000"
    volumes:
      - .:/GrimReaper/ambulance
