version: "3.8"
services:

  visualizer:
    build: .
    image: dockersamples/visualizer:stable
    ports:
      - "8088:8088"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]