version: "3"
services:

  GrimReaperFront:
    container_name: react-app
    image: docker-react-i
    build:
      context: GrimReaperFront
    ports:
      - "3000:3000"

  patient:
    build:
      context: patient
      dockerfile: Dockerfile
    container_name: patientcontainer
    command: uvicorn patient.index:app --host 0.0.0.0 --port 8008 --reload --reload-include *
    ports:
      - "8008:8008"
    volumes:
      - .:/GrimReaper/patient


  user:
    build: 
      context: user
      dockerfile: Dockerfile
    container_name: usercontainer
    command: uvicorn user.index:app --host 0.0.0.0 --port 80 --reload --reload-include *
    ports:
      - "80:80"
    volumes:
      - .:/GrimReaper/user


  ambulance:
    build: 
      context: ambulance
      dockerfile: Dockerfile
    container_name: ambulancecontainer
    command: uvicorn ambulance.index:app --host 0.0.0.0 --port 8000 --reload --reload-include *
    ports:
      - "8000:8000"
    volumes:
      - .:/GrimReaper/ambulance
  
  api-gateway:
    build: 
      context: api-gateway
      dockerfile: Dockerfile
    container_name: api-gatewaycontainer
    command: uvicorn api-gateway.index:app --host 0.0.0.0 --port 8080 --reload --reload-include *
    ports:
      - "8080:8080"
    volumes:
      - .:/GrimReaper/api-gateway


  master:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://api-gateway:8080
  worker:
    image: locustio/locust
    volumes:
      - ./:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master


  


